# Generated by Django 5.0.4 on 2024-05-12 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Достижения', 'verbose_name_plural': '►Достижения'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': '►Образование'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Языки', 'verbose_name_plural': '►Международные языки'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Персональная информация', 'verbose_name_plural': '►Персональная информация'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': '►Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='programmingframework',
            options={'verbose_name': 'Фреймворки', 'verbose_name_plural': '►Фреймворки'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Работа', 'verbose_name_plural': '►Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': '►Мои услуги'},
        ),
        migrations.AlterModelOptions(
            name='workreview',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': '►Отзывы'},
        ),
        migrations.AddField(
            model_name='language',
            name='language_level',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('certificate_path',)},
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='personalinfo',
            unique_together={('vk_link', 'tg_link', 'github_link', 'linkedin_link')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('github_link',)},
        ),
        migrations.AlterUniqueTogether(
            name='programmingframework',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name',)},
        ),
        migrations.AlterModelTable(
            name='personalinfo',
            table='dict_entities',
        ),
    ]
