# Generated by Django 5.0.4 on 2024-05-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_award_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэги', 'verbose_name_plural': '►Тэги'},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name',)},
        ),
        migrations.AlterModelTable(
            name='personalinfo',
            table=None,
        ),
    ]
